["protostar.config"]
protostar_version = "0.2.6"

["protostar.project"]
libs_path = "./lib"

["protostar.contracts"]
zk_barter_v1 = [
    "./src/zk_barter_v1.cairo",
]
proxy = [
    "./src/proxy_delegate.cairo",
]
erc721 = [
    "./lib/cairo_contracts/src/openzeppelin/token/erc721/ERC721_Mintable_Burnable.cairo"
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]